### ISSUE TITLE
Hardcoded prefix gets added to paths

### ISSUE THREAD

**Issue by nullmove** [piotrklibert/ffipf#1]
Hello, nice idea for this package. I am trying it out now and I get hardcoded home path prefix (possibly from your development):

![](https://paste.gnugen.ch/paste/Ce02)

Additionally, I would like to say that a similar package named [find-file-in-project](https://github.com/technomancy/find-file-in-project) already provides a function called `ffip`. It would be nice if yours could be renamed to prevent clashing.

**Comment by piotrklibert** [comment]
You're 100% right, I left my home dir in the code, I had no time to get it cleaned up properly during the weekend. I totally rushed the release, because I really wanted to quickly learn if there's any interest in this kind of package. Turned out much better than I expected, with over 50 upvotes on _r/emacs_ (yay!), so now I'm motivated to actually take this a bit more seriously :)

For now, I renamed everything from `ffip` to `ffipf` - I'm still waiting for a better name idea... - and renamed `ffip.nim` to `ffipf_backend.nim`, so the DLL is now `ffipf_backend.so`, which makes it possible to `require` it instead of `load`ing. I cleaned up all the hardcoded paths, including in the (currently just 1...) test, and updated the README with a bit of Elisp I use to run the module. While it's nowhere near finished just yet, I believe it should be much better than yesterday's sorry state.

I will be working on it for the next few weeks at least, so if you have any questions or suggestions I'm always happy to hear them :)

**Comment by nullmove** [comment]
It works now, thanks! There aren't that many libraries that uses the new module system so it's always exciting to see a new one, and architecturally dynamic modules are definitely sounder and cooler than subprocess.

Anyway, I don't really have suggestion. It seems to work in terms of what you set out to do. However, I do feel like while fuzzy matching is cool and all, it probably doesn't match the utility of good old literal/regex search. Most of the time I just want to match substring so literal search is both fastest and narrowest. Also I use prescient/ivy which has nice feature of producing orderless substring match. For example, I have a sizeable documents folder, and let's say I want to read a book but all I recall about it is that it has "optimization" and "python" in its name. Using either of the word produces too many result (>20), and currently with ffipf I am not having much luck finding the book named "Serge Kruk - Practical Python AI Projects_ Mathematical Models of Optimization Problems with Google OR-Tools-Apress (2018).epub" with either order of "optimization python" or "python optimization".

**Comment by piotrklibert** [comment]
This matching algorithm is definitely geared more towards typical programming project directory hierarchies - the deeper the hierarchy, the better it works, in my experience. This is by design, I think (I'm not the author, I just ported it from Ruby.) For fuzzily matching words in any order, and for long, non-uniformly formatted filenames, the algorithm used by Ivy is better. I thought about making `SPC` work as it does in Ivy, and it shouldn't be difficult to implement, but I didn't have the chance to do it yet. It might be a good idea, actually! The same goes for matching parts of the pattern exactly as written, although making it the default would kind of defeat the purpose of the project :D

As for the algorithm itself, I realized today that I should use additional weights for file extensions, so that `*.so`, which is not something I'd open with Emacs, is below `*.nim` (for example). I have the file extension blacklist, but for some extensions, it would be nice to still see the file in the list, just further down. Another idea would be to include a recency score in the final score, but I'm not sure how useful it would be. Generally, the more processing is done in Nim, the more of an advantage this package will have in terms of performance over alternatives, which is another (after convenience) reason I'll be working on improving the algorithm/backend first; the current frontend is simplistic, but it works for me quite well, so it's not a priority at the moment.
